feat: card with icons component
Bateyjosue/ojemba-team-project pull request #5
Opened 2023-08-17 14:14 UTC by Kevinemug

done with card with icon component

2023-08-18 10:13 UTC, Angekarara requested changes
those three paragraphs on each icon has to be 20px not 16px

2023-08-18 10:13 UTC, Angekarara commented on src/Components/cardWithIcon.html
> +    <p class="text-white font-montRegular text-[16px]"> niedriges Lohnkostenniveau im europäischen Vergleich</p>
the text has to be 20 px not 16px

2023-08-18 10:13 UTC, Angekarara commented on src/Components/cardWithIcon.html
> +    <p class="text-white font-montRegular text-[16px]"> niedriges Lohnkostenniveau im europäischen Vergleich</p>
this text has to be 20px too

2023-08-18 10:13 UTC, Angekarara commented on src/Components/cardWithIcon.html
> +    <p class="text-white font-montRegular text-[16px]"> niedriges Lohnkostenniveau im europäischen Vergleich</p>
this text has to be 20px too

2023-08-19 12:33 UTC, HIRWA13 approved these changes
Hi team, the changes you made matches the ones that we requested now I see that the design is good you can merge!

2023-08-20 10:16 UTC, merged