fet: kotakt footer
Bateyjosue/ojemba-team-project pull request #9
Opened 2023-08-18 15:37 UTC by Bateyjosue

## Task: [#OJMBWP-28]
### Description
In this PR, We work on: 
- [ ] Title with
- [ ] contact Button
- [ ] footer with logo with
- [ ] footer navigation
### Screenshot
![kotakt](https://github.com/Bateyjosue/ojemba-team-project/assets/52311487/65e4f103-f8c4-40d2-aa22-07222eefb51f)

## Cheers 🎉 🎉 🎉

2023-08-19 11:03 UTC, HIRWA13 requested changes
measurements are good but try to match the same design as it is designed on the figma!

![footer review](https://github.com/Bateyjosue/ojemba-team-project/assets/117777634/3e4284f4-f4a0-4d8d-abbc-c0ccc5fa0ef3)

2023-08-19 12:09 UTC, Bateyjosue commented
Hey @HIRWA13, I have seen your comments on this PR.  but I'm A bit confused because i don't know which measurement you are talking about. 
Please be Specific

**Thanks For talking time to review this PR**

##

> Don't forget to tag me on @Bateyjosue so that I get notified

2023-08-21 10:18 UTC, HIRWA13 approved these changes
Hi @Bateyjosue, thanks for applying the changes that were missing on the footer.!
After reviewing both the footer and the kontakt section I can see that nothing is missing there.

you can merge this branch to dev.

2023-08-21 10:52 UTC, Kevinemug commented on src/Components/kotakt.html
> +<div class="bg-white transform skew-y-3 ">
I liked how you perfected the skewing dimensions

2023-08-21 10:52 UTC, Kevinemug approved these changes
hello @Bateyjosue  I approved your PR

2023-08-21 12:46 UTC, merged